title: Sheet bend - the most useful knot
hero_image: images/banner.jpg
description: One knot that can perform in almost any situation
version: 4
listed: false
copyedit: false
last_tested: "2018-04-16"
site_areas: HackSpace
steps:
  - title: Introduction
  - title: Start with a loop
  - title: Threading the needle
  - title: Finishing the knot
